apiVersion: v1
kind: Secret
metadata:
  name: techdoc-overlay
  namespace: tap-install
stringData:
  techdoc-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata":{"name":"server"}, "kind": "Deployment"})
    ---
    spec:
      template:
        spec:
          #@overlay/replace
          securityContext:
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
            fsGroup: 0
          volumes:
            - emptyDir: {}
              name: tmp
            - emptyDir: {}
              name: output
          containers:
            #@overlay/match by="name"
            - name: backstage
              #@overlay/replace
              env:
                - name: DOCKER_HOST
                  value: 'tcp://localhost:2375'
              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                - mountPath: /output
                  name: output
            - args:
              command:
              - dockerd
              - '--host'
              - 'tcp://127.0.0.1:2375'
              env:
                - name: DOCKER_HOST
                  value: 'tcp://localhost:2375'
              image: 'docker:24.0.0-rc.1-dind'
              imagePullPolicy: IfNotPresent
              name: dind-daemon
              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                - mountPath: /output
                  name: output
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              securityContext:
                runAsUser: 0
                privileged: true